services:
  deployer:
    image: node:22-alpine
    working_dir: /app/scripts
    command: node deployContracts.js
    environment:
      ENV_FILE: /app/.env
    volumes:
      - ../..:/app
    networks:
      - eil-network-demo

networks:
  eil-network-demo:
    name: eil-network-demo
    driver: bridge
    external: true
